services:
  apache:
    container_name: apache
    image: romannichiporuk/apache
    ports:
      - 8080:8080
    networks:
      - br0
  
  nginx:
    user: nginx
    container_name: nginx
    image: romannichiporuk/nginx
    ports:
      - 81:80
    networks:
      - br0
    volumes:
      - /etc/ssl/self-signed:/home/ubuntu
    depends_on:
      - apache
networks:
  br0:
    driver: bridge
