services:
  apache:
    container_name: apache
    image: nichiporukroman/my-apache-image:latest
    ports:
      - 8080:8080
    networks:
      - br0
  
  nginx:
    user: nginx
    container_name: nginx
    image: nichiporukroman/my-nginx-image:test
    ports:
      - 81:80
    networks:
      - br0
    volumes:
      - /etc/ssl/self-signed:/home/ubuntu
    depends_on:
      - apache

networks:
  br0:
    driver: bridge

