services:
  apache:
    container_name: apache
    image: nichiporukroman/my-apache-image:latest
    ports:
      - 8080:8080
    networks:
      - br0
  
  nginx:
    user: nginx
    container_name: nginx
    image: nichiporukroman/my-nginx-image:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - br0
    volumes:
      - /etc/ssl/self-signed:/etc/nginx/certs
    depends_on:
      - apache

networks:
  br0:
    driver: bridge

