# Tasks file for Docker installation
- name: Install Docker on Ubuntu
  apt:
    name: 
      - docker-compose
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker on Amazon Linux
  script: /home/roman/playsdev-tranee/tasks/task_15/docker-compose.sh
  when: ansible_os_family == "RedHat"
