# Tasks file for Docker installation
- name: Install Docker on Ubuntu
  apt:
    name: 
      - docker-compose
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker on Amazon Linux
  script: '{{ docker_compose_install_amazon }}'
  when: ansible_os_family == "RedHat"
