FROM ubuntu:22.04
    
    
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y apache2 \
    php \
    libapache2-mod-php \
    tzdata

    
COPY ./apache.conf /etc/apache2/sites-available/000-default.conf


COPY ./info.php /var/www/html/info.php


EXPOSE 80


ENTRYPOINT ["apache2ctl", "-D", "FOREGROUND"]
