- name: Deploy docker and docker-compose on instances
  hosts: all
  become: true

  vars:
    git_repo_url: "https://github.com/NichiporukRoman/playsdev-repository.git"
    git_dest: "/home/ubuntu1/"

  roles: 
    - role: docker
      tags: docker

    - role: git
      tags: git 

    - role: make-certs
      tags: make-certs 

    - role: docker-build
      tags: docker-build