- name: Deploy docker and docker-compose on instances
  hosts: all
  become: true

  roles: 
    - role: docker
      tags: docker

    - role: git
      tags: git 

    - role: make-certs
      tags: make-certs 

    - role: docker-build
      tags: docker-build