all:
  children:
    web:
      hosts:
        3.91.32.83:
          ansible_user: ec2-user
          ansible_port: 22
          ansible_ssh_private_key_file: /home/roman/Documents/noire.pem
        3.90.109.115:
          ansible_user: ubuntu
          ansible_port: 22
          ansible_ssh_private_key_file: /home/roman/Documents/noire.pem
ansible_python_interpreter: /usr/bin/python3
