web:
  hosts:
    98.84.126.15:
      ansible_user: ubuntu
      ansible_port: 22
      ansible_ssh_private_key_file: /home/roman/Documents/noire.pem
  vars:
    ansible_python_interpreter: /usr/bin/python3
