- name: Backup original GitLab configuration
  copy:
    src: /etc/gitlab/gitlab.rb
    dest: /etc/gitlab/gitlab.rb.bak
    remote_src: yes
    mode: '0644'

- name: Update external_url in GitLab configuration
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^external_url '.*'"
    line: "external_url 'http://{{ gitlab_domain }}'"
    state: present

- name: Reduce Puma workers to optimize memory usage
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^puma['worker_processes'] =.*"
    line: "puma['worker_processes'] = 1"
    state: present
    create: yes

- name: Reduce Sidekiq concurrency
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^sidekiq['concurrency'] =.*"
    line: "sidekiq['concurrency'] = 5"
    state: present
    create: yes

- name: Lower PostgreSQL shared buffers
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^postgresql['shared_buffers'] =.*"
    line: "postgresql['shared_buffers'] = '256MB'"
    state: present
    create: yes

- name: Disable Prometheus monitoring
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^prometheus_monitoring['enable'] =.*"
    line: "prometheus_monitoring['enable'] = false"
    state: present
    create: yes

- name: Disable Container Registry
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^registry['enable'] =.*"
    line: "registry['enable'] = false"
    state: present
    create: yes

- name: Configure Swap Space
  block:
    - name: Create a 2GB swap file
      shell: |
        fallocate -l 2G /swapfile
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile

    - name: Add swapfile to fstab
      lineinfile:
        path: /etc/fstab
        line: "/swapfile none swap sw 0 0"
        state: present

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  args:
    executable: /bin/bash

- name: Restart GitLab to apply changes
  shell: gitlab-ctl restart
  args:
    executable: /bin/bash