FROM nginx:alpine

RUN apk add --no-cache \
    aws-cli \
    openssl \
    bash \
    curl \ 
    sudo 

COPY script.sh /usr/local/bin/generate-htpasswd.sh
RUN chmod +x /usr/local/bin/generate-htpasswd.sh

COPY cronfile /etc/cron.d/update-htpasswd-cron
RUN chmod 0777 /etc/cron.d/update-htpasswd-cron

RUN crontab /etc/cron.d/update-htpasswd-cron

RUN /usr/local/bin/generate-htpasswd.sh

COPY nginx.conf /etc/nginx/nginx.conf

USER root

CMD ["sh", "-c", "crond && exec nginx -g 'daemon off;'"]
